services:
  laravel-app:
    build: ./laravel-app/
    ports:
      - "8181:8181" 
    volumes:
     - .:/laravel-app/
    depends_on:
      - mysql

  mysql: 
    image: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
       - "127.0.0.1:3306:3306"

  vue-project:
     build: ./vue-project/
     ports:  
      - 5173:5173 
     volumes:
      - .:/vue-project/
     depends_on:
      - mysql